### PR TITLE
Add page for the architecture diagram

### PR DESCRIPTION
**Pull request by tijmenb**
This diagram contains almost all applications and the relationships between them. It's permanent work in progress.

### CODE REVIEW

**Comment by h-lame** [comment]
👏 Typo on the image: "Blue line means B writes from A" probably should be "Purple line means B writes to A"

**Comment by h-lame** [comment]
Oh, also, don't suppose the image is available as SVG / graphviz / some other textual format so it's easier to update?

**Comment by davidbasalla** [comment]
Is Licensify the missing app you mentioned at TechSAD? Do I win? 😛

**Comment by tijmenb** [comment]
@davidbasalla It isn't, but I did forget it! There's at least one more :)

**Comment by surminus** [comment]
Just spotted this PR - this is super useful. I wonder if @stephenharker has any further diagrams we could add here?

**Pull request merged**
