### PR TITLE
Change to Operations Manual

### PR DESCRIPTION
**Pull request by surminus**
Everything in this part of the manual used to be in the opsmanual, so
change the title to reflect it's mostly about operations.

### CODE REVIEW

**Comment by tijmenb** [comment]
So it's _mostly_ about operations, but not entirely (https://docs.publishing.service.gov.uk/manual/ab-testing.html, https://docs.publishing.service.gov.uk/manual/keeping-software-current.html for example). Plus I'm hoping there's going to be more docs & guides in this section (the RFCs, how to upgrade to newer rails version, what libraries to use). 

The reason not to call it Opsmanual was that it might easily be confused with the old Opsmanual, which unfortunately needed to stay around. "Operations manual" might have the same problem?

**Comment by surminus** [comment]
Hmm, I think you're probably right, "dev manual" just sounds like it's for developers rather than anyone else. I'm not sure now.

**Comment by tijmenb** [comment]
"Tech manual", or maybe just "Manual"?

**Comment by MatMoore** [comment]
Devops manual!

**Comment by nickcolley** [comment]
It should definitely reflect Ops not be generic 👍

**Comment by surminus** [comment]
Tech Manual would work for me.

**Comment by tijmenb** [comment]
New attempt: https://github.com/alphagov/govuk-developer-docs/pull/170

**Pull request closed without merging**
