### PR TITLE
Add playbook entry for check_cdn_log_s3_freshness Icinga alert.

### PR DESCRIPTION
**Pull request by sengi**
See alphagov/govuk-puppet#10113.

### CODE REVIEW

**Comment by sengi** [comment]
Oh yikes I just found https://docs.publishing.service.gov.uk/manual/alerts/logs-are-not-being-received-from-the-cdn.html which is very similar, but it turns out we have two log ingestion pipelines which both take the Fastly logs. Apparently that's for the other one (the non-S3 one).

**Comment by issyl0** [comment]
We should probably ditch the non-S3 one. It pre-dates the S3 and Athena stuff and feels silly to have both - if Amazon goes down we've got bigger problems. 🤔

**Comment by issyl0** [comment]
Also the docs for the manual way still reference the "deployment" repo, so they're very old.

**Comment by issyl0** [comment]
So I looked into this a bit further and I think we _can_ remove the non-AWS code and docs.

The ["Fastly error rate"](https://docs.publishing.service.gov.uk/manual/alerts/fastly-error-rate.html) alert [pulls from the Fastly APIs](https://github.com/alphagov/govuk-puppet/blob/fad3d3b903389a0e145e47d27bc8f7708bfa41f6/modules/collectd/manifests/plugin/cdn_fastly.pp) via the [collectd-cdn](https://github.com/gds-operations/collectd-cdn/blob/master/collectd_cdn/fastly.py) plugin.

**Comment by sengi** [comment]
> So I looked into this a bit further and I think we _can_ remove the non-AWS code and docs.
> 
> The ["Fastly error rate"](https://docs.publishing.service.gov.uk/manual/alerts/fastly-error-rate.html) alert [pulls from the Fastly APIs](https://github.com/alphagov/govuk-puppet/blob/fad3d3b903389a0e145e47d27bc8f7708bfa41f6/modules/collectd/manifests/plugin/cdn_fastly.pp) via the [collectd-cdn](https://github.com/gds-operations/collectd-cdn/blob/master/collectd_cdn/fastly.py) plugin. It doesn't use the files on the monitoring machine disk.

Awesome. Thanks, Issy! I'll follow up with a PR to remove the old stuff then.

**Comment by issyl0** [comment]
The other, confusing docs are gone now.

**Comment by sengi** [comment]
> The other, confusing docs are gone now.

Thanks!

**Pull request merged**
