### PR TITLE
Review more out of date docs for 2nd line

### PR DESCRIPTION
**Pull request by thomasleese**
These pages look up to date to me.

### CODE REVIEW

**Comment by issyl0** [comment]
> -   This check is there to flag up potential problems occurring upstream
    -- a service not returning fast enough so we have the set write
    connecting building up. This was a pattern spotted in a number of
    recent outages as at April 2013.

Maybe remove the word "recent"? 🧓Also I am astonished that nothing has changed since 2013 and that we still have this at all, but...

**Comment by thomasleese** [comment]
> > * This check is there to flag up potential problems occurring upstream
> >   -- a service not returning fast enough so we have the set write
> >   connecting building up. This was a pattern spotted in a number of
> >   recent outages as at April 2013.
> 
> Maybe remove the word "recent"? 🧓Also I am astonished that nothing has changed since 2013 and that we still have this at all, but...

Yes, I was half tempted to remove that alert and document because I don't remember it happening at any point, but I didn't feel confident enough!

**Comment by issyl0** [comment]
I'd remove it, if we need it we can put it back. Looking at Icinga it hasn't fired in... 154 days?

**Comment by thomasleese** [comment]
> I'd remove it, if we need it we can put it back. Looking at Icinga it hasn't fired in... 154 days (and probably way beyond that, I don't know how far back Icinga's data goes...)?

Cool, I've opened a PR to remove it!

**Pull request merged**
