### PR TITLE
Update GOV.UK architecture diagram

### PR DESCRIPTION
**Pull request by tijmenb**
Changes:

- Content performance manager doesn't talk to content-store anymore 🎉 
- The 3 apps that use the Whitehall organisations API now use collections (because the `/api/organisations` route is now served by that). I think this means that Whitehall doesn't have an API anymore? @sihugh or @rubenarakelyan to confirm.
- Added govuk-content-quality-service
- Update: email-alert-api is no longer talking to GovDelivery
- Added link checker, Licensify, DGU to the "Not pictured" section

### CODE REVIEW

**Comment by sihugh** [comment]
We've only migrated the orgs api.  There are still `government`, `worldwide_location` and `worldwide_organisation` apis in Whitehall.  https://github.com/alphagov/whitehall/blob/b361148f2103527b4be04f34d3d6a3ead1ae8b3e/config/routes.rb#L33-L40

I'll be removing the org api bits soon

**Comment by tijmenb** [comment]
@sihugh thanks! Do you know if any of those APIs are used internally? Or externally for that matter?

**Comment by bevanloon** [comment]
Do the registers team still use the whitehall api? I think they might have used the `/organisations` at some point.

**Comment by sihugh** [comment]
Registers (and other people) definitely use the organisations api endpoint.  I'm just doing some digging into the others

**Comment by bevanloon** [comment]
`world-locations` too by the looks: https://github.com/openregister/country-data/blob/master/lists/world/bin/world.py#L6

**Comment by cbaines** [comment]
I'm not sure about the `rummager` - `smartanswers` link, I can't see either app directly talking to the other.

**Comment by tijmenb** [comment]
@cbaines good spot!

**Pull request merged**
