### PR TITLE
Update architecture diagram March 2018

### PR DESCRIPTION
**Pull request by tijmenb**
This is the regular update of the GOV.UK architecture diagram.

The thing: https://github.com/alphagov/govuk-developer-docs/raw/update-architecture/source/manual/images/govuk-architecture.jpg

Changes:

- email-alert-api is now talking to, and receiving requests from, GOV.UK Notify
- content-performance-manager is exposed as an API
- content-audit-tool is a new application
- Minor style updates

Anything missing @alphagov/gov-uk ?

### CODE REVIEW

**Comment by MatMoore** [comment]
Stuff is written to content-performance-manager via the message queue now, so there should be another line there (cc @peteglondon)

**Comment by rubenarakelyan** [comment]
`email-alery-frontend` reads from and writes to `email-alert-api`

**Comment by pmanrubia** [comment]
> Stuff is written to content-performance-manager via the message queue now, so there should be another line there (cc @peteglondon)

@tijmenb @MatMoore @peteglondon, some additional information if you find this useful.

Content Performance Manager:
- reads from the `Content Store` to retrieve the full JSON of content items
- reads from `Support-API` to retrieve anonymous contacts by day
- reads from `Publishing-API` to retrieve `live` content and basic metadata (title & description)

**Comment by kevindew** [comment]
These apps read/write to Email Alert API (creating/redirecting subscriptions):

- Whitehall
- Collections
- Finder Frontend

These apps write to Publishing API at deploy time, which may not be something we care about for this diagram (and is not exhaustive):

- Rummager
- Frontend
- Smart Answers

Mainstream publisher reads from Calendars

Manuals Publisher reads from Whitehall Admin (looking up organisations)

**Comment by tijmenb** [comment]
Thanks all, I've updated the diagram. Should be good for review now.

**Pull request merged**
