### PR TITLE
Update review status element

### PR DESCRIPTION
**Pull request by tijmenb**
This updates the review status element on the manual pages.

- Displays the date of the last review so the reader knows whether or not the page is likely to be accurate 
- Fixes relative dates module
- Updates design

See commits for details.

## Before

screen shot 2017-11-16 at 10 56 23

## After

screen shot 2017-11-16 at 10 56 26

### CODE REVIEW

**Comment by tijmenb** [comment]
To fix:

https://govuk-tech-docs-pr-579.herokuapp.com/manual/dns.html

> This page was last reviewed 185 days ago. It needs to be reviewed again 1 days ago by the page owner #2ndline.

https://govuk-tech-docs-pr-579.herokuapp.com/manual/rebooting-machines.html

> This page was last reviewed 94 days ago. It needs to be reviewed again 3 months from now by the page owner #2ndline.

**Comment by nickcolley** [comment]
Looks good, I think we can do less and remove the blue background potentially though?

**Comment by tijmenb** [comment]
Without using the blue banner the element looks a bit lost, blurring in between the related items and the footer (View source / Report problem / GitHub Repo).

screen shot 2017-11-21 at 12 07 19

The blue banner breaks up the page a bit, which I think makes it more easier to distinguish the elements.

screen shot 2017-11-21 at 12 08 09

In terms of priority, last reviewed date is the most important metadata that we provide. It's roughly analogous to the Publishing metadata component in the new GOV.UK designs (https://gov-uk.atlassian.net/wiki/spaces/GFED/pages/186351726/Sprint+1+designs), that's why I chose the (existing) blue banner.

**Comment by tuzz** [comment]
Is the `#name` referring to a Slack channel? Would it be possible to link to the web URL for this?

**Pull request merged**
