### PR TITLE
Make review_by easier to work with

### PR DESCRIPTION
**Pull request by tijmenb**
Since the `review_by` date was introduced I've seen a few questions come up around what a good review date is (https://github.com/alphagov/govuk-developer-docs/pull/183 for example). I've also noticed that I find it hard to pick a good date (since it involves some arithmetic).

This PR tries make it easier by replacing `review_by` with `last_reviewed_at` and `review_in`. The idea is that you don't have to think about the dates anymore, just insert todays date.

Thoughts?

### CODE REVIEW

**Comment by 36degrees** [comment]
Seems like a sensible approach.

Looks like some of the content is being nuked (by the script?) as part of the PR though.

**Comment by tomnatt** [comment]
Seeing the hard coded Slack channels raises some questions for me about the ownership. The channels are tied to the teams, and the teams change so we'll need to review all of the ownerships in detail every quarter.

That doesn't affect this PR though - it's a good change.

**Comment by tijmenb** [comment]
Updated PR.

**Comment by timblair** [comment]
In Ruby-land, due to ActiveRecord, an `_at` suffix implies a datetime. For just a date, I'd prefer `last_reviewed_on`.

**Pull request merged**
